### ISSUE TITLE
[BUG] If nullable after type then nullable: true is ignored.

### ISSUE THREAD

**Issue by Bogdan1001** [nehero/validate#26]
Hello,

When we use `Validate.validate(nil, type: :string, nullable: true, min: 10)`, and have `nullable: true` set after type: string, then an error will be raised.

I believe this behavior is incorrect, and order must be ignored here, so I am raising an issue. :)

**Comment by ozziexsh** [comment]
Hey it is shown in the docs but not explicitly stated that nullable always has to be first:

https://github.com/ozziexsh/validate?tab=readme-ov-file#nullable

i will update the docs to reflect that, but it is intended for now
